---
title: "EDA"
author: "James A. Coppock, Cyrus Tanade, Nicole Zimmer"
date: "9/25/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## BME 590: Fall Detection

```{r cars}
#setwd("~/Desktop/Duke/Class/Fall 2020/Biomedical DS/BME590_Fall_Detection")
#install.packages("Rcpproll")
#install.packages("slider")
library(RcppRoll)
library(slider)
library(tibble)
library(purrr)
library(lubridate, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(readxl)
library(evobiR)
library(patchwork)
library(gridExtra)
library(moments)
library(corrplot)
library(corrr)
library(signal)
```

```{r}
Falls_df1 <- read.csv('Fall_Data1.csv')
Falls_df2 <- read.csv('Fall_Data2.csv')
Falls_df  <- rbind(Falls_df1,Falls_df2)
Falls_df_rms <- rbind(Falls_df1,Falls_df2)
rm(Falls_df1)
rm(Falls_df2)
```


See structure of dataset

```{r}
str(Falls_df)
str(Falls_df_rms)
```

```{r}

bf <- signal::butter(4, 1/49, type="low")

Time <- Falls_df$Time
accX <- signal::filtfilt(bf, Falls_df_rms$accX)
accY <- signal::filtfilt(bf, Falls_df_rms$accY)
accZ <- signal::filtfilt(bf, Falls_df_rms$accZ)
  
angX <- signal::filtfilt(bf, Falls_df_rms$angX)
angY <- signal::filtfilt(bf, Falls_df_rms$angY)
angZ <- signal::filtfilt(bf, Falls_df_rms$angZ)
  
maxX <- signal::filtfilt(bf, Falls_df_rms$maxX)
magY <- signal::filtfilt(bf, Falls_df_rms$magY)
magZ <- signal::filtfilt(bf, Falls_df_rms$magZ)

Target <- Falls_df$Target

Falls_df <- data.frame(Time, accX, accY, accZ, angX, angY, angZ, maxX, magY, magZ, Target)
# Falls_df_rms <- data.frame(Time, accX, accY, accZ, angX, angY, angZ, maxX, magY, magZ, Target)

```

Make a new dataset of RMS values

```{r}
# 
# Falls_df_rms <- dplyr::mutate(Falls_df_rms, acc = (Falls_df_rms$accX^2 + Falls_df_rms$accY^2 + Falls_df_rms$accZ^2)^0.5)
# Falls_df_rms <- dplyr::mutate(Falls_df_rms, ang = (Falls_df_rms$angX^2 + Falls_df_rms$angY^2 + Falls_df_rms$angZ^2)^0.5)
# Falls_df_rms <- dplyr::mutate(Falls_df_rms, mag = (Falls_df_rms$maxX^2 + Falls_df_rms$magY^2 + Falls_df_rms$magZ^2)^0.5)
# 
# Falls_df_rms <- dplyr::select(Falls_df_rms, Time, acc, ang, mag, Target)
# 
# str(Falls_df_rms)

```

```{r}

Falls_raw_none <- dplyr::filter(Falls_df, Target == 0)
Falls_raw_target <- dplyr::filter(Falls_df, Target == 1)

Falls_df_none <- dplyr::filter(Falls_df_rms, Target == 0)
Falls_df_target <- dplyr::filter(Falls_df_rms, Target == 1)

```


```{r}
Falls_df_rms[, "Target"] <- sapply(Falls_df_rms[, "Target"], as.factor)
Falls_df[, "Target"] <- sapply(Falls_df_rms[, "Target"], as.factor)
```


```{r, fig.width=15, fig.height=6}
library(ggplot2)

cols <- c("#2E9FDF", "#FF6666")

accX <- ggplot(Falls_df, aes(x=accX, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Acceleration (m/s^2)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$accX)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$accX)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,1)+ theme(text=element_text(size=17))

accY <- ggplot(Falls_df, aes(x=accY, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Acceleration (m/s^2)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$accY)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$accY)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,1)+theme(text=element_text(size=17))

accZ <- ggplot(Falls_df, aes(x=accZ, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Acceleration (m/s^2)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$accZ)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$accZ)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,1)+theme(text=element_text(size=17))

angX <- ggplot(Falls_df, aes(x=angX, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Angular Rotation (Rad/s)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$angX)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$angX)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,2.5)+ theme(text=element_text(size=17))

angY <- ggplot(Falls_df, aes(x=angY, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Angular Rotation (Rad/s)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$angY)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$angY)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,2.5)+ theme(text=element_text(size=17))

angZ <- ggplot(Falls_df, aes(x=accZ, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Angular Rotation (Rad/s)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$accZ)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$accZ)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,2.5)+ theme(text=element_text(size=17))

magX <- ggplot(Falls_df, aes(x=maxX, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Magnetic Flux Density (uT)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$maxX)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$maxX)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,6.5)+ theme(text=element_text(size=17))

magY <- ggplot(Falls_df, aes(x=magY, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Magnetic Flux Density (uT)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$magY)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$magY)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,6.5)+ theme(text=element_text(size=17))

magZ <- ggplot(Falls_df, aes(x=magZ, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Magnetic Flux Density (uT)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_raw_none$magZ)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_raw_target$magZ)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,6.5)+ theme(text=element_text(size=17))

a <- ggplot(Falls_df_rms, aes(x=acc, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Acceleration (m/s^2)") + 
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_df_none$acc)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_df_target$acc)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,1)

b <- ggplot(Falls_df_rms, aes(x=ang, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Angular Rotation (Rad/s)") +
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_df_none$ang)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_df_target$ang)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,2.5)

c <- ggplot(Falls_df_rms, aes(x=mag, color=Target)) +
  geom_histogram(aes(y=..density..), bins=50) + xlab("Magnetic Flux Density (uT)") +
  ylab("Density") + scale_color_manual(values=cols) +
  geom_vline(aes(xintercept = mean(Falls_df_none$mag)),col='#2E9FDF', linetype="dashed") +
  geom_vline(aes(xintercept = mean(Falls_df_target$mag)),col='#FF6666', linetype="dashed") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylim(0,6.5)

(accX+accY+accZ)/
(angX+angY+angZ)/
(magX+magY+magZ)
```
```{r}
x<-Falls_df$accY
del<-1/100 # sampling interval
x.spec <- spectrum(x,log="no",span=500,plot=FALSE)
spx <- x.spec$freq/del
spy <- 2*x.spec$spec
plot(spy~spx,xlab="frequency",ylab="spectral density",type="l")
```
```{r}
x<-Falls_df_rms$accY
del<-1/100 # sampling interval
x.spec <- spectrum(x,log="no",span=500,plot=FALSE)
spx <- x.spec$freq/del
spy <- 2*x.spec$spec
plot(spy~spx,xlab="frequency",ylab="spectral density",type="l")
```


```{r}

accX + accY + accZ + a + plot_layout(ncol = 4, nrow = 1, guides = "collect") + ggsave("histogram_acc.png", height = 2 , width = 10)

```

```{r}

angX + angY + angZ + b + plot_layout(ncol = 4, nrow = 1, guides = "collect") + ggsave("histogram_ang.png", height = 2 , width = 10)

```



```{r}

magX + magY + magZ + c + plot_layout(ncol = 4, nrow = 1, guides = "collect") + ggsave("histogram_mag.png", height = 2 , width = 10)

```



```{r}
sum(Falls_df$Target[Falls_df$Target==1])
```



```{r, fig.width=10, fig.height=4}

p <- ggplot(Falls_df_rms, aes(x=Target, y=acc)) + 
  geom_boxplot(outlier.shape=NA) + ylab("Acceleration (m/s^2)") + coord_flip() +
  scale_y_continuous(limits = quantile(Falls_df_rms$acc, c(0.2, 0.8))) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

q <- ggplot(Falls_df_rms, aes(x=Target, y=ang)) + 
  geom_boxplot(outlier.shape=NA) + ylab("Angular Rotation (Rad/s)") + coord_flip() +
  scale_y_continuous(limits = quantile(Falls_df_rms$ang, c(0.1, 0.9))) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

r <- ggplot(Falls_df_rms, aes(x=Target, y=mag)) + 
  geom_boxplot(outlier.shape=NA) + ylab("Magnetic Flux Density (uT)") + coord_flip() +
  scale_y_continuous(limits = quantile(Falls_df_rms$mag, c(0.1, 0.9))) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

p + q + r + plot_annotation(
  title = 'Boxplots for Sensor Data (without outliers)') + ggsave("boxplot_no_outlier.png", height = 2 , width = 10)

```


```{r, fig.width=10, fig.height=4}

p <- ggplot(Falls_df_rms, aes(x=Target, y=acc)) + 
  geom_boxplot() + ylab("Acceleration (m/s^2)") + coord_flip() +
  scale_y_continuous(limits = quantile(Falls_df_rms$acc, c(0, 1))) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

q <- ggplot(Falls_df_rms, aes(x=Target, y=ang)) + 
  geom_boxplot() + ylab("Angular Rotation (Rad/s)") + coord_flip() +
  scale_y_continuous(limits = quantile(Falls_df_rms$ang, c(0, 1))) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

r <- ggplot(Falls_df_rms, aes(x=Target, y=mag)) + 
  geom_boxplot() + ylab("Magnetic Flux Density (uT)") + coord_flip() +
  scale_y_continuous(limits = quantile(Falls_df_rms$mag, c(0, 1))) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"))

p + q + r + plot_annotation(
  title = 'Boxplots for Sensor Data') + ggsave("boxplot_outlier.png", height = 2 , width = 10)

```


```{r}

cat('The Number of Falls in this Set of Data is:',(sum(Falls_df$Target)),'\n')

```



## Including Plots

You can also embed plots, for example:

```{r , echo=FALSE}
cat('The Number of Falls in this Set of Data is:',(sum(Falls_df$Target)),'\n')
Fs <- 100
win <- 2
stp <- 0.5
window <-win*Fs
step <- stp*Fs
```

```{r}

Falls_df_rms[, "Target"] <- sapply(Falls_df_rms[, "Target"], as.numeric)

test_fun <- function(x) {
   max(x)
}

rms <- function(x){
  sqrt(sum(x^2)/length(x))
}

q1 <- function(x){
  quantile(x, 0.25)
}

q3 <- function(x){
  quantile(x, 0.75)
}

rename <- function(a,b,c){
  var_name <- paste(c, a, sep="_") # Construct the name
  assign(var_name, b, env=.GlobalEnv) # Assign values to variable
}

variable_generate <- function(a){
  arg_name <- deparse(substitute(a))
  
  mean_var <- SlidingWindow("mean", abs(a), window, step)
  rename(arg_name,mean_var, "mean")
  
  max_var <- SlidingWindow("max", abs(a), window, step)
  rename(arg_name,max_var, "max")
  
  min_var <- SlidingWindow("min", abs(a), window, step)
  rename(arg_name,min_var, "min")
  
  median_var <- SlidingWindow("median", abs(a), window, step)
  rename(arg_name,median_var, "median")
  
  q1_var <- SlidingWindow("q1", abs(a), window, step)
  rename(arg_name,q1_var, "q1")
  
  q3_var <- SlidingWindow("q3", abs(a), window, step)
  rename(arg_name,q3_var, "q3")
  
  std_var <- SlidingWindow("sd", abs(a), window, step)
  rename(arg_name,std_var, "std")

  skew_var <- SlidingWindow("skewness", abs(a), window, step)
  rename(arg_name,skew_var, "skew")
  
  kurtosis_var <- SlidingWindow("kurtosis", abs(a), window, step)
  rename(arg_name,kurtosis_var, "kurtosis")
}

#mean, standard deviation, RMS, max and min amplitude, Q1 median and Q3, skewness, kurtosis
#test<-roll_mean(Falls_df$accX,n =25,by = 12 )
Targets<-SlidingWindow("max", Falls_df$Target, window, step)
maxAccX<-SlidingWindow(max, abs(Falls_df$accX), window, step)
maxAccXTest<-SlidingWindow(test_fun, abs(Falls_df$accX), window, step)
maxAccY<-SlidingWindow("max", abs(Falls_df$accY), window, step)
maxAccZ<-SlidingWindow("max", abs(Falls_df$accZ), window, step)
#maxAccX[0:20]
#maxAccXTest[0:20]
#mean, standard deviation, RMS, max and min amplitude, Q1 median and Q3, skewness, kurtosis
Features<-data.frame(cbind(maxAccX,maxAccY,maxAccZ, Targets))
Features
#stats_AccX

# Feature Extraction
#variable_generate(Falls_df$accX)
#variable_generate(Falls_df$accY)
#variable_generate(Falls_df$accZ)
#variable_generate(Falls_df$angX)
#variable_generate(Falls_df$angY)
#variable_generate(Falls_df$angZ)
#variable_generate(Falls_df$magY)
#variable_generate(Falls_df$magZ)

Targets<-SlidingWindow("max", Falls_df_rms$Target, window, step)
variable_generate(Falls_df_rms$acc)
variable_generate(Falls_df_rms$ang)
variable_generate(Falls_df_rms$mag)

```


```{r}

# Combine all features into a dataframe
#AllFeatures <- data.frame(Targets, `mean_Falls_df$accX`, `max_Falls_df$accX`, `min_Falls_df$accX`,`median_Falls_df$accX`,`q1_Falls_df$accX`,
#                                  `q3_Falls_df$accX`,`rms_Falls_df$accX`,`std_Falls_df$accX`,`skew_Falls_df$accX`,`kurtosis_Falls_df$accX`,
#                                   `mean_Falls_df$accY`, `max_Falls_df$accY`, `min_Falls_df$accY`,`median_Falls_df$accY`,`q1_Falls_df$accY`,
#                                  `q3_Falls_df$accY`,`rms_Falls_df$accY`,`std_Falls_df$accY`,`skew_Falls_df$accY`,`kurtosis_Falls_df$accY`,
#                                   `mean_Falls_df$accZ`, `max_Falls_df$accZ`, `min_Falls_df$accZ`,`median_Falls_df$accZ`,`q1_Falls_df$accZ`,
#                                  `q3_Falls_df$accZ`,`rms_Falls_df$accZ`,`std_Falls_df$accZ`,`skew_Falls_df$accZ`,`kurtosis_Falls_df$accZ`, 
#                                   `mean_Falls_df$angX`,`max_Falls_df$angX`,`min_Falls_df$angX`,`median_Falls_df$angX`,`q1_Falls_df$angX`,
#                                  `q3_Falls_df$angX`,`rms_Falls_df$angX`, `std_Falls_df$angX`,`skew_Falls_df$angX`,`kurtosis_Falls_df$angX`,
#                                   `mean_Falls_df$angY`,`max_Falls_df$angY`,`min_Falls_df$angY`,`median_Falls_df$angY`,`q1_Falls_df$angY`,
#                                  `q3_Falls_df$angY`,`rms_Falls_df$angY`,`std_Falls_df$angY`,`skew_Falls_df$angY`,`kurtosis_Falls_df$angY`,
#                                   `mean_Falls_df$angZ`,`max_Falls_df$angZ`,`min_Falls_df$angZ`,`median_Falls_df$angZ`,`q1_Falls_df$angZ`,
#                                  `q3_Falls_df$angZ`,`rms_Falls_df$angZ`,`std_Falls_df$angZ`,`skew_Falls_df$angZ`,`kurtosis_Falls_df$angZ`,
#                                   `mean_Falls_df$magY`,`max_Falls_df$magY`,`min_Falls_df$magY`,`median_Falls_df$magY`,`q1_Falls_df$magY`,
#                                  `q3_Falls_df$magY`,`rms_Falls_df$magY`,`std_Falls_df$magY`,`skew_Falls_df$magY`,`kurtosis_Falls_df$magY`,
#                                   `mean_Falls_df$magZ`,`max_Falls_df$magZ`,`min_Falls_df$magZ`,`median_Falls_df$magZ`,`q1_Falls_df$magZ`,
#                                  `q3_Falls_df$magZ`,`rms_Falls_df$magZ`,`std_Falls_df$magZ`,`skew_Falls_df$magZ`,`kurtosis_Falls_df$magZ`)

# lol please tell me there's a better way to do this ^

#str(AllFeatures)
AllFeaturesRMS <- data.frame(Targets,`mean_Falls_df_rms$acc`,`max_Falls_df_rms$acc`,`min_Falls_df_rms$acc`,`median_Falls_df_rms$acc`,`q1_Falls_df_rms$acc`,
                                    `q3_Falls_df_rms$acc`,`std_Falls_df_rms$acc`,`skew_Falls_df_rms$acc`,`kurtosis_Falls_df_rms$acc`,
                                     `mean_Falls_df_rms$ang`,`max_Falls_df_rms$ang`,`min_Falls_df_rms$ang`,`median_Falls_df_rms$ang`,`q1_Falls_df_rms$ang`,
                                    `q3_Falls_df_rms$ang`,`std_Falls_df_rms$ang`,`skew_Falls_df_rms$ang`,`kurtosis_Falls_df_rms$ang`,
                                     `mean_Falls_df_rms$mag`,`max_Falls_df_rms$mag`,`min_Falls_df_rms$mag`,`median_Falls_df_rms$mag`,`q1_Falls_df_rms$mag`,
                                    `q3_Falls_df_rms$mag`,`std_Falls_df_rms$mag`,`skew_Falls_df_rms$mag`,`kurtosis_Falls_df_rms$mag`)

# Check that there are still 28 falls
names(AllFeaturesRMS)[2] <- "Mean(acc)"
names(AllFeaturesRMS)[3] <- "Max(acc)"
names(AllFeaturesRMS)[4] <- "Min(acc)"
names(AllFeaturesRMS)[5] <- "Median(acc)"
names(AllFeaturesRMS)[6] <- "Q1(acc)"
names(AllFeaturesRMS)[7] <- "Q3(acc)"
names(AllFeaturesRMS)[8] <- "SD(acc)"
names(AllFeaturesRMS)[9] <- "Skew(acc)"
names(AllFeaturesRMS)[10] <- "Kurtosis(acc)"

names(AllFeaturesRMS)[11] <- "Mean(ang)"
names(AllFeaturesRMS)[12] <- "Max(ang)"
names(AllFeaturesRMS)[13] <- "Min(ang)"
names(AllFeaturesRMS)[14] <- "Median(ang)"
names(AllFeaturesRMS)[15] <- "Q1(ang)"
names(AllFeaturesRMS)[16] <- "Q3(ang)"
names(AllFeaturesRMS)[17] <- "SD(ang)"
names(AllFeaturesRMS)[18] <- "Skew(ang)"
names(AllFeaturesRMS)[19] <- "Kurtosis(ang)"

names(AllFeaturesRMS)[20] <- "Mean(mag)"
names(AllFeaturesRMS)[21] <- "Max(mag)"
names(AllFeaturesRMS)[22] <- "Min(mag)"
names(AllFeaturesRMS)[23] <- "Median(mag)"
names(AllFeaturesRMS)[24] <- "Q1(mag)"
names(AllFeaturesRMS)[25] <- "Q3(mag)"
names(AllFeaturesRMS)[26] <- "SD(mag)"
names(AllFeaturesRMS)[27] <- "Skew(mag)"
names(AllFeaturesRMS)[28] <- "Kurtosis(mag)"

colnames(AllFeaturesRMS)
cat('The Number of Falls in this Set of Data is:',(sum(AllFeaturesRMS$Targets)),'\n')
```


```{r}


varPlot <- AllFeaturesRMS$`Mean(acc)`

freedman_diaconis <- function(x){
  2 * IQR(x) / length(x)^(1/3)
}

p <- ggplot(AllFeaturesRMS, aes(x=varPlot)) + 
 geom_histogram(aes(y=..density..), fill="white", color="black", binwidth=freedman_diaconis(varPlot))
p

```




```{r}
# Correlation plot
#colnames(AllFeaturesRMS) <- paste0("f", 1:ncol(AllFeaturesRMS))

col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
# use corrplot library
cor_df <- cor(AllFeaturesRMS)
corrplot(cor_df, method = "color", type = "lower", col=col(200),
         diag=FALSE, order="hclust", tl.cex = 0.5)

```

```{r}
x <- AllFeaturesRMS %>% 
  correlate() %>% 
  focus(Targets)

x <- mutate(x, Legend = ifelse(x$Targets>0, "Positive Correlation", "Negative Correlation"))

x

colors <- c("Negative Correlation" = "#BB4444", "Positive Correlation" = "#4477AA")

x %>% 
  mutate(rowname = factor(rowname, levels = rowname[order(Targets)])) %>%  # Order by correlation strength
  ggplot(aes(x = rowname, y = Targets, fill = Legend)) +
    geom_bar(stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylim(-0.1, 0.1) +
    ggtitle("Correlation of Falls (Label) with Features") +   scale_fill_manual(values=c("#BB4444", "#4477AA")) +
    labs(x = "Feature", y = "Pearson's Correlation") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_blank(), axis.line = element_line(colour = "black")) + ggsave("correlation.png", height = 3 , width = 3 * 3.5)
```


```{r , echo=FALSE}
time<-seq(from = 1/Fs, to =(length(Falls_df$accX)/Fs) , by = 1/Fs)
wintime<-seq(from = 1/100, to =(length(Features$maxAccX)/2) , by = 1/2)

p2<-ggplot(data=Features, aes(x = wintime, y=maxAccX, group=1)) +
  geom_line(linetype = "solid") + labs(title = "Max X Acceleration in (2:0.5) Window") 

p2
```

```{r}
yhat<-as.logical(Falls_df$Target)
fX<-Falls_df$accX[yhat]
fY<-Falls_df$accY[yhat]
fZ<-Falls_df$accZ[yhat]
X<-time[yhat]
feat<-data.frame(cbind(X,fX,fY,fZ))
p1<-ggplot(data=Falls_df, aes(x = time, y=accX, group=1)) +
  geom_line(linetype = "solid") + labs(title = "X Acceleration") + geom_point(data=feat, aes(x = X, y=fX, group=2,color = 'Falls'))
p2<-ggplot(data=Falls_df, aes(x = time, y=accY, group=1)) +
  geom_line(linetype = "solid") + labs(title = "Y Acceleration") + geom_point(data=feat, aes(x = X, y=fY, group=2,color = 'Falls'))
p3<-ggplot(data=Falls_df, aes(x = time, y=accZ, group=1)) +
  geom_line(linetype = "solid") + labs(title = "Z Acceleration") + geom_point(data=feat, aes(x = X, y=fZ, group=2,color = 'Falls'))

p1/p2/p3
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
